version: '2'
services:
  redis:
      image: "redis:latest"
      container_name: redis
      restart: unless-stopped
      ports:
        - "6379:6379"
      volumes:
       - "./Dockerfiles/redis.conf:/etc/redis.conf:ro"
      command: "redis-server /etc/redis.conf"
  web:
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile
    container_name: wikiclient
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    links:
      - redis:redis
    volumes:
      - ./config_prod.py:/usr/local/etc/wikiclient/config.py:ro
    ports:
    - "8082:8080"
    command: wikiclient